### ISSUE TITLE
No module named 'cached_property'

### ISSUE THREAD

**Issue by cultpenguin** [usgs/geobipy#26]
Hi 

When I import geobipy (fter a fresh install) I get the following: 
```
(geobipy) tmeha@pop-os:~/space/PROGRAMMING/geobipy/documentation_source/source/examples/Models$ python
Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geobipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/__init__.py", line 21, in <module>
    from .src.base import customFunctions
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/base/customFunctions.py", line 5, in <module>
    from ..classes.core import StatArray
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/classes/core/StatArray.py", line 12, in <module>
    from ...base.HDF import hdfRead
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/base/HDF/hdfRead.py", line 6, in <module>
    from ...classes.data.datapoint.FdemDataPoint import FdemDataPoint
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/classes/data/datapoint/FdemDataPoint.py", line 7, in <module>
    from .EmDataPoint import EmDataPoint
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/classes/data/datapoint/EmDataPoint.py", line 1, in <module>
    from .DataPoint import DataPoint
  File "/mnt/space/PROGRAMMING/geobipy/geobipy/src/classes/data/datapoint/DataPoint.py", line 1, in <module>
    from cached_property import cached_property
ModuleNotFoundError: No module named 'cached_property'

```
Am I missing something ?

- Thomas

**Comment by leonfoks** [comment]
Hey Thomas,

I added cached properties for speed.  You will need to "pip install cached_property".

I've updated the dependencies in the setup.py file.

Thanks!

**Comment by cultpenguin** [comment]
Thanx. 
Perhaps you should also add 'empymod', that seems to be needed to run some of the examples.
See you
- Thomas
